Repository MidasXIV/anavrin, pull requests merged in 2020-08, with the labels that each got.

#5 Add prettier and eslint support
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  package.json
Labels: dev-tools

#3 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/development-goal.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: github

#9 Run ESlint and Prettier on codebase
  .eslintrc.json
  src/components/app-header/index.tsx
  src/components/dropdown-menu/index.tsx
  src/components/index.tsx
  src/components/loading/index.tsx
  src/components/menu/index.tsx
  src/controllers/dividendController.ts
  src/pages/_app.tsx
  src/pages/api/dividend.js
  src/pages/api/dividendHistory.js
  src/pages/dashboard.tsx
  src/pages/index.tsx
  src/util/useOutsideClick.ts
Labels: refactor

#10 Add Tailwind CSS to Anavrin
  package-lock.json
  package.json
  postcss.config.js
  src/pages/_app.tsx
  src/styles/index.css
  tailwind.config.js
Labels: dev-tools

#11 Migrate styling from styled-jsx to Tailwind CSS
  package.json
  public/global.css
  src/components/app-header/index.tsx
  src/components/loading/index.tsx
  src/components/menu/index.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/dashboard.tsx
  src/pages/index.tsx
  src/pages/portfolio.tsx
  src/styles/index.css
  tailwind.config.js
Labels: refactor
